language: java

jdk:
  - oraclejdk8

services:
  - docker

branches:
  only:
    - 0.1.x

script:
  # push to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export TAG0=latest
  - export TAG1=`cat ./src/main/resources/.version`
  - docker build -t $REPO:$TAG0 .
  - docker build -t $REPO:$TAG1 .
  - docker push $REPO:$TAG0
  - docker push $REPO:$TAG1
  # push to github releases
  - mvn clean package -Dmaven.test.skip=true --batch-mode --quiet

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "$GITHUB_USER_NAME"
  - git config --local user.email "$GITHUB_USER_MAIL"
  - export TRAVIS_TAG=`cat ./src/main/resources/.version`
  - git tag $TRAVIS_TAG

deploy:
  provider: releases

  api_key: "$GITHUB_OAUTH_TOKEN"

  file:
    - "./target/redis-rdb-cli-release.tar.gz"
    - "./target/redis-rdb-cli-release.zip"

  skip_cleanup: true

  # on:
  #   tags: true